image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - CollisionLib2D/bin/

test:
    stage: test
    script: 
        - "dotnet test"
        
deploy:
  stage: deploy
  script:
    - dotnet pack -c Release
    - dotnet nuget push "CollisionLib2D/bin/Release/*.nupkg" --api-key $NugetApiKey  --source https://api.nuget.org/v3/index.json
  only:
    - master